name: Publish release
on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed
jobs:
  pypi-publish:
    if: github.repository_owner == 'oauthlib' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/oauthlib
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install prereq
      run: pip install wheel
    - name: Build python package
      run: python setup.py build
    - name: Package python package
      run: python setup.py sdist bdist_wheel
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
